### ISSUE TITLE
program running error

### ISSUE THREAD

**Issue by KajiMaCN** [XiaoxinHe/TAPE#17]
Hello,
I'm getting some errors when running trainLM.py:

```
Traceback (most recent call last):
  File "/root/anaconda3/envs/TAPE/lib/python3.8/site-packages/transformers/utils/import_utils.py", line 1472, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/root/anaconda3/envs/TAPE/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/anaconda3/envs/TAPE/lib/python3.8/site-packages/transformers/training_args.py", line 75, in <module>
    from .trainer_pt_utils import AcceleratorConfig
  File "/root/anaconda3/envs/TAPE/lib/python3.8/site-packages/transformers/trainer_pt_utils.py", line 37, in <module>
    from torch.optim.lr_scheduler import LRScheduler
ImportError: cannot import name 'LRScheduler' from 'torch.optim.lr_scheduler' (/root/anaconda3/envs/TAPE/lib/python3.8/site-packages/torch/optim/lr_scheduler.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "trainLM.py", line 1, in <module>
    from LMs.lm_trainer import LMTrainer
  File "/workspace/core/LMs/lm_trainer.py", line 4, in <module>
    from transformers import AutoTokenizer, AutoModel, TrainingArguments, Trainer, IntervalStrategy
  File "<frozen importlib._bootstrap>", line 1039, in _handle_fromlist
  File "/root/anaconda3/envs/TAPE/lib/python3.8/site-packages/transformers/utils/import_utils.py", line 1462, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/root/anaconda3/envs/TAPE/lib/python3.8/site-packages/transformers/utils/import_utils.py", line 1474, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.training_args because of the following error (look up to see its traceback):
cannot import name 'LRScheduler' from 'torch.optim.lr_scheduler' (/root/anaconda3/envs/TAPE/lib/python3.8/site-packages/torch/optim/lr_scheduler.py)
```

**Comment by KajiMaCN** [comment]
vim /root/anaconda3/envs/TAPE/lib/python3.8/site-packages/transformers/trainer_pt_utils.py 
`from torch.optim.lr_scheduler import LRScheduler` change to `from torch.optim.lr_scheduler import _LRScheduler as LRScheduler`
