### ISSUE TITLE
training error

### ISSUE THREAD

**Issue by KajiMaCN** [XiaoxinHe/TAPE#18]
D:\anaconda3\envs\TAPE\lib\site-packages\accelerate\accelerator.py:432: FutureWarning: Passing the following arguments to `Accelerator` is deprecated and will be removed in version 1.0 of Accelerate: dict_keys(['dispatch_batches', 'split_batches', 'even_batches', 'use_seedable_sampler']). Please pass an `accelerate.DataLoaderConfiguration` instead: 
dataloader_config = DataLoaderConfiguration(dispatch_batches=None, split_batches=False, even_batches=True, use_seedable_sampler=True)
  warnings.warn(
Traceback (most recent call last):
  File "E:\PycharmProjects\TAPE-main\core\trainLM.py", line 24, in <module>
    run(cfg)
  File "E:\PycharmProjects\TAPE-main\core\trainLM.py", line 12, in run
    trainer.train()
  File "E:\PycharmProjects\TAPE-main\core\utils.py", line 80, in wrapper
    ret = func(*args, **kw)
  File "E:\PycharmProjects\TAPE-main\core\LMs\lm_trainer.py", line 119, in train
    self.trainer.train()
  File "D:\anaconda3\envs\TAPE\lib\site-packages\transformers\trainer.py", line 1624, in train
    return inner_training_loop(
  File "D:\anaconda3\envs\TAPE\lib\site-packages\transformers\trainer.py", line 1653, in _inner_training_loop
    train_dataloader = self.get_train_dataloader()
  File "D:\anaconda3\envs\TAPE\lib\site-packages\transformers\trainer.py", line 852, in get_train_dataloader
    return self.accelerator.prepare(DataLoader(train_dataset, **dataloader_params))
  File "D:\anaconda3\envs\TAPE\lib\site-packages\torch\utils\data\dataloader.py", line 238, in __init__
    assert prefetch_factor > 0
TypeError: '>' not supported between instances of 'NoneType' and 'int'

**Comment by XiaoxinHe** [comment]
It appears to be a Python environment issue rather than a technical issue related to this project.
